"""
Phase 6 tests — AWS deployment artifacts.

What's tested here, and why these specific things:

1. .dockerignore correctness — a regression test for the real bug
   caught during development: a bare `*.db` pattern would have
   silently excluded data/sensors.db (needed at build time by
   Dockerfile.sensor) while only INTENDING to exclude the MCP servers'
   runtime-generated databases.

2. Dockerfile COPY paths actually exist in the repo.

3. mcp_servers/*.py DB/log paths are correctly overridable via env var
   — this is what lets docker-compose mount a volume at /app/data
   instead of shadowing /app/mcp_servers (the second real bug caught
   during development).

4. aws/lambda/handler.py correctly wraps each of the 4 lightweight
   FastAPI apps via Mangum, including the explicit init_db() call this
   project needs since lifespan="off" means FastAPI's lifespan context
   manager (which would otherwise create the SQLite tables) never runs.

5. aws/lambda/package.py and aws/eventbridge/deploy.py's packaging
   logic produce the expected file sets — verified by actually running
   the packaging functions and inspecting the resulting zip contents,
   not just reading the code.

6. aws/eventbridge/scheduler_handler.py's pure-logic helpers
   (_persist_trace, _extract_severity) work correctly in both local
   and S3 modes (S3 calls are mocked — no real AWS needed).

None of these tests require Docker, real AWS credentials, or live MCP
servers — they validate the deployment ARTIFACTS and PACKAGING LOGIC,
which is exactly what's reliably testable without a real cloud account.

Run:
    cd asset_health_monitor
    pytest tests/test_phase6.py -v
"""

import fnmatch
import json
import sys
import zipfile
from pathlib import Path

import pytest

ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT))


# ---------------------------------------------------------------------------
# .dockerignore correctness
# ---------------------------------------------------------------------------

class TestDockerignore:
    @pytest.fixture
    def patterns(self):
        with open(ROOT / ".dockerignore") as f:
            return [line.strip() for line in f if line.strip() and not line.startswith("#")]

    def _is_excluded(self, path: str, patterns: list[str]) -> bool:
        return any(fnmatch.fnmatch(path, p) for p in patterns)

    def test_sensors_db_is_NOT_excluded(self, patterns):
        """
        Regression test: data/sensors.db must be INCLUDED in the Docker
        build context, since Dockerfile.sensor's `COPY data/ ./data/`
        depends on it existing at build time. A bare `*.db` pattern
        would silently break this.
        """
        assert not self._is_excluded("data/sensors.db", patterns)

    def test_mcp_server_databases_ARE_excluded(self, patterns):
        """These are runtime-generated by each server's init_db() — never needed at build time."""
        for path in ["mcp_servers/cmms.db", "mcp_servers/inventory.db",
                     "mcp_servers/scheduling.db", "mcp_servers/alerts.log"]:
            assert self._is_excluded(path, patterns), f"{path} should be excluded but isn't"

    def test_sensors_db_wal_shm_sidecars_excluded(self, patterns):
        """
        WAL/SHM sidecar files only exist while a local process has the
        DB open — copying them in mid-write would leave an inconsistent
        database inside the image.
        """
        assert self._is_excluded("data/sensors.db-wal", patterns)
        assert self._is_excluded("data/sensors.db-shm", patterns)

    def test_env_file_excluded(self, patterns):
        assert self._is_excluded(".env", patterns)


# ---------------------------------------------------------------------------
# Dockerfile COPY paths exist
# ---------------------------------------------------------------------------

class TestDockerfilePaths:
    def test_sensor_dockerfile_copy_paths_exist(self):
        required = [
            "mcp_servers/sensor_mcp.py", "mcp_servers/schemas.py",
            "mcp_servers/__init__.py", "models", "data",
        ]
        for path in required:
            assert (ROOT / path).exists(), f"Dockerfile.sensor COPYs {path} but it doesn't exist"

    def test_lightweight_dockerfile_copy_paths_exist(self):
        assert (ROOT / "mcp_servers").exists()

    def test_both_dockerfiles_install_httpx(self):
        """
        Regression test: docker-compose's healthcheck runs `python -c
        "import httpx; ..."` inside each container — neither Dockerfile
        installed httpx originally, which made every healthcheck fail.
        """
        sensor_df = (ROOT / "docker" / "Dockerfile.sensor").read_text()
        lightweight_df = (ROOT / "docker" / "Dockerfile.lightweight").read_text()
        assert "httpx" in sensor_df
        assert "httpx" in lightweight_df


# ---------------------------------------------------------------------------
# docker-compose.yml volume mount correctness
# ---------------------------------------------------------------------------

class TestDockerComposeVolumes:
    @pytest.fixture
    def compose_text(self):
        return (ROOT / "docker-compose.yml").read_text()

    def test_no_volume_mounted_directly_over_mcp_servers_code_dir(self, compose_text):
        """
        Regression test: mounting a named volume at /app/mcp_servers
        would shadow the application code COPY'd there at build time,
        causing every lightweight server to fail to import on startup.
        Checks specifically for that as a VOLUME MOUNT TARGET (the
        ":/app/mcp_servers" pattern docker-compose uses), not just any
        mention of "mcp_servers" — the file's own comments legitimately
        reference mcp_servers/ by name elsewhere.
        """
        assert ":/app/mcp_servers" not in compose_text

    def test_volumes_mounted_at_dedicated_data_dir(self, compose_text):
        assert "/app/data" in compose_text

    def test_each_lightweight_service_sets_its_db_path_env_var(self, compose_text):
        for env_var in ["CMMS_DB_PATH", "INVENTORY_DB_PATH", "SCHEDULING_DB_PATH", "NOTIFY_LOG_PATH"]:
            assert env_var in compose_text


# ---------------------------------------------------------------------------
# mcp_servers/*.py DB path env var overrides (the actual code, not just compose)
# ---------------------------------------------------------------------------

class TestServerDbPathOverrides:
    """
    These four servers must respect an env var override for their
    DB/log path — this is what docker-compose's volume-at-/app/data
    fix above actually depends on at the application level.
    """

    def test_cmms_db_path_respects_env_var(self, monkeypatch, tmp_path):
        monkeypatch.setenv("CMMS_DB_PATH", str(tmp_path / "custom_cmms.db"))
        import importlib
        import mcp_servers.cmms_mcp as mod
        importlib.reload(mod)
        assert str(mod.DB_PATH) == str(tmp_path / "custom_cmms.db")

    def test_inventory_db_path_respects_env_var(self, monkeypatch, tmp_path):
        monkeypatch.setenv("INVENTORY_DB_PATH", str(tmp_path / "custom_inventory.db"))
        import importlib
        import mcp_servers.inventory_mcp as mod
        importlib.reload(mod)
        assert str(mod.DB_PATH) == str(tmp_path / "custom_inventory.db")

    def test_scheduling_db_path_respects_env_var(self, monkeypatch, tmp_path):
        monkeypatch.setenv("SCHEDULING_DB_PATH", str(tmp_path / "custom_scheduling.db"))
        import importlib
        import mcp_servers.scheduling_mcp as mod
        importlib.reload(mod)
        assert str(mod.DB_PATH) == str(tmp_path / "custom_scheduling.db")

    def test_notify_log_path_respects_env_var(self, monkeypatch, tmp_path):
        monkeypatch.setenv("NOTIFY_LOG_PATH", str(tmp_path / "custom_alerts.log"))
        import importlib
        import mcp_servers.notify_mcp as mod
        importlib.reload(mod)
        assert str(mod.LOG_PATH) == str(tmp_path / "custom_alerts.log")

    def test_default_paths_unchanged_when_env_var_not_set(self, monkeypatch):
        """Without the env var, behavior must match pre-Phase-6 local dev exactly."""
        monkeypatch.delenv("CMMS_DB_PATH", raising=False)
        import importlib
        import mcp_servers.cmms_mcp as mod
        importlib.reload(mod)
        assert mod.DB_PATH == Path(mod.__file__).parent / "cmms.db"


# ---------------------------------------------------------------------------
# aws/lambda/handler.py
# ---------------------------------------------------------------------------

class TestLambdaHandler:
    def _invoke(self, module: str, method: str, path: str, body: str | None = None) -> dict:
        """Helper: load handler.py fresh with a given MCP_SERVER_MODULE and invoke it."""
        import importlib.util
        spec = importlib.util.spec_from_file_location(
            "handler_mod", ROOT / "aws" / "lambda" / "handler.py"
        )
        handler_mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(handler_mod)

        event = {
            "version": "2.0",
            "routeKey": f"{method} {path}",
            "rawPath": path,
            "rawQueryString": "",
            "headers": {"host": "localhost", "content-type": "application/json"},
            "requestContext": {
                "http": {"method": method, "path": path, "sourceIp": "127.0.0.1"},
                "stage": "$default",
            },
            "isBase64Encoded": False,
        }
        if body is not None:
            event["body"] = body

        class FakeContext:
            function_name = "test"
            memory_limit_in_mb = 128
            aws_request_id = "test-request-id"

        return handler_mod.handler(event, FakeContext())

    def test_cmms_health_check(self, monkeypatch, tmp_path):
        monkeypatch.setenv("MCP_SERVER_MODULE", "mcp_servers.cmms_mcp:app")
        monkeypatch.setenv("CMMS_DB_PATH", str(tmp_path / "cmms.db"))
        response = self._invoke("mcp_servers.cmms_mcp:app", "GET", "/health")
        assert response["statusCode"] == 200
        assert "cmms-mcp" in response["body"]

    def test_cmms_create_work_order_via_lambda(self, monkeypatch, tmp_path):
        """
        Regression test: with lifespan="off", FastAPI's lifespan context
        manager never fires, so init_db() must be called explicitly by
        handler.py itself — otherwise this fails with
        'no such table: work_orders' on the very first request.
        """
        monkeypatch.setenv("MCP_SERVER_MODULE", "mcp_servers.cmms_mcp:app")
        monkeypatch.setenv("CMMS_DB_PATH", str(tmp_path / "cmms.db"))
        body = json.dumps({
            "machine_id": "PUMP-01", "fault_type": "bearing_wear",
            "description": "test", "priority": "high",
        })
        response = self._invoke("mcp_servers.cmms_mcp:app", "POST", "/work_orders", body)
        assert response["statusCode"] == 200
        parsed = json.loads(response["body"])
        assert parsed["status"] == "open"

    def test_inventory_health_check(self, monkeypatch, tmp_path):
        monkeypatch.setenv("MCP_SERVER_MODULE", "mcp_servers.inventory_mcp:app")
        monkeypatch.setenv("INVENTORY_DB_PATH", str(tmp_path / "inventory.db"))
        response = self._invoke("mcp_servers.inventory_mcp:app", "GET", "/health")
        assert response["statusCode"] == 200

    def test_inventory_parts_seeded_via_lambda(self, monkeypatch, tmp_path):
        """Same init_db() concern as cmms — inventory's seed data must appear on first request."""
        monkeypatch.setenv("MCP_SERVER_MODULE", "mcp_servers.inventory_mcp:app")
        monkeypatch.setenv("INVENTORY_DB_PATH", str(tmp_path / "inventory.db"))
        response = self._invoke("mcp_servers.inventory_mcp:app", "GET", "/parts")
        assert response["statusCode"] == 200
        assert len(json.loads(response["body"])) == 8

    def test_scheduling_health_check(self, monkeypatch, tmp_path):
        monkeypatch.setenv("MCP_SERVER_MODULE", "mcp_servers.scheduling_mcp:app")
        monkeypatch.setenv("SCHEDULING_DB_PATH", str(tmp_path / "scheduling.db"))
        response = self._invoke("mcp_servers.scheduling_mcp:app", "GET", "/health")
        assert response["statusCode"] == 200

    def test_notify_health_check(self, monkeypatch, tmp_path):
        """notify-mcp has no init_db() at all — handler.py's hasattr guard must not break on this."""
        monkeypatch.setenv("MCP_SERVER_MODULE", "mcp_servers.notify_mcp:app")
        monkeypatch.setenv("NOTIFY_LOG_PATH", str(tmp_path / "alerts.log"))
        response = self._invoke("mcp_servers.notify_mcp:app", "GET", "/health")
        assert response["statusCode"] == 200


# ---------------------------------------------------------------------------
# aws/lambda/package.py
# ---------------------------------------------------------------------------

class TestLambdaPackaging:
    def test_package_contains_handler_and_four_servers(self, tmp_path, monkeypatch):
        import importlib.util
        spec = importlib.util.spec_from_file_location("package_mod", ROOT / "aws" / "lambda" / "package.py")
        package_mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(package_mod)

        # LAMBDA_DIR must stay pointing at the real aws/lambda/ folder,
        # since that's where handler.py (one of the files being
        # packaged) actually lives — only redirect the output path and
        # leave BUILD_DIR pointed at a guaranteed-absent directory so
        # this test exercises the no-dependencies warning path, the
        # same way TestEventBridgePackaging does.
        monkeypatch.setattr(package_mod, "BUILD_DIR", tmp_path / "_build_never_created")

        out_path = package_mod.build_package(output_path=tmp_path / "package.zip")

        with zipfile.ZipFile(out_path) as zf:
            names = zf.namelist()

        assert "handler.py" in names
        for server in ["cmms_mcp.py", "inventory_mcp.py", "scheduling_mcp.py", "notify_mcp.py", "schemas.py", "__init__.py"]:
            assert f"mcp_servers/{server}" in names
        # sensor_mcp.py deliberately excluded — needs torch, not a Lambda fit
        assert "mcp_servers/sensor_mcp.py" not in names


# ---------------------------------------------------------------------------
# aws/eventbridge/deploy.py packaging
# ---------------------------------------------------------------------------

class TestEventBridgePackaging:
    def test_orchestrator_package_contains_only_agent_and_data(self, tmp_path, monkeypatch):
        import importlib.util
        spec = importlib.util.spec_from_file_location(
            "eb_deploy_mod", ROOT / "aws" / "eventbridge" / "deploy.py"
        )
        eb_deploy_mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(eb_deploy_mod)

        # Only redirect where the staging dir + output zip get built —
        # EVENTBRIDGE_DIR must stay pointing at the real aws/eventbridge/
        # folder, since that's where scheduler_handler.py (the file being
        # packaged) actually lives. build_orchestrator_package() always
        # reads FROM EVENTBRIDGE_DIR and the project ROOT, regardless of
        # where staging happens — so we only need to redirect the BUILD_DIR
        # check (kept absent here, deliberately, to exercise the
        # no-dependencies warning path) and the final output path.
        monkeypatch.setattr(eb_deploy_mod, "ORCHESTRATOR_PACKAGE", tmp_path / "orchestrator_package.zip")

        out_path = eb_deploy_mod.build_orchestrator_package()

        with zipfile.ZipFile(out_path) as zf:
            names = zf.namelist()

        assert "scheduler_handler.py" in names
        assert "agent/react_agent.py" in names
        assert "data/store.py" in names

        # Regression check: models/ and mcp_servers/ were bundled
        # unnecessarily in an early draft — neither is actually imported
        # by the orchestrator's real code path (verified empirically
        # during development by tracking sys.modules before/after the
        # actual import statements).
        assert not any(n.startswith("models/") for n in names)
        assert not any(n.startswith("mcp_servers/") for n in names)


# ---------------------------------------------------------------------------
# aws/eventbridge/scheduler_handler.py pure-logic helpers
# ---------------------------------------------------------------------------

class TestSchedulerHandlerHelpers:
    def test_extract_severity_finds_anomaly_score_step(self):
        from aws.eventbridge.scheduler_handler import _extract_severity
        trace = {"steps": [
            {"tool_name": "get_anomaly_score", "tool_output": {"severity": "critical"}},
        ]}
        assert _extract_severity(trace) == "critical"

    def test_extract_severity_returns_none_when_absent(self):
        from aws.eventbridge.scheduler_handler import _extract_severity
        trace = {"steps": [{"tool_name": "create_work_order", "tool_output": {"status": "open"}}]}
        assert _extract_severity(trace) is None

    def test_persist_trace_local_mode(self, tmp_path, monkeypatch):
        monkeypatch.delenv("TRACE_BUCKET", raising=False)
        import importlib
        import aws.eventbridge.scheduler_handler as mod
        importlib.reload(mod)

        # Redirect the local-mode output dir into tmp_path
        monkeypatch.setattr(
            "aws.eventbridge.scheduler_handler.Path",
            mod.Path,  # no-op patch placeholder; real redirect below
        )
        # Easiest robust approach: monkeypatch __file__'s parent chain by
        # calling the function and checking the real default location,
        # then cleaning up — avoids over-mocking Path itself.
        trace = {"machine_id": "TEST-MACHINE", "steps": [], "n_steps": 0}
        mod._persist_trace(trace)

        expected = ROOT / "agent" / "traces" / "TEST-MACHINE.json"
        assert expected.exists()
        with open(expected) as f:
            assert json.load(f)["machine_id"] == "TEST-MACHINE"
        expected.unlink()  # cleanup — don't leave test residue in agent/traces/

    def test_persist_trace_s3_mode(self, monkeypatch):
        import unittest.mock as mock
        monkeypatch.setenv("TRACE_BUCKET", "fake-test-bucket")
        import importlib
        import aws.eventbridge.scheduler_handler as mod
        importlib.reload(mod)

        with mock.patch("boto3.client") as mock_boto:
            mock_s3 = mock.MagicMock()
            mock_boto.return_value = mock_s3

            trace = {"machine_id": "MOTOR-01", "steps": [], "n_steps": 0}
            mod._persist_trace(trace)

            assert mock_s3.put_object.called
            kwargs = mock_s3.put_object.call_args.kwargs
            assert kwargs["Bucket"] == "fake-test-bucket"
            assert kwargs["Key"] == "traces/MOTOR-01.json"
            assert kwargs["ContentType"] == "application/json"
